# Generated by Django 5.0.3 on 2024-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.TextField(default='1'),
        ),
    ]
