# Generated by Django 5.0.3 on 2024-03-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='srvice_description',
            new_name='service_description',
        ),
    ]
