# Generated by Django 5.0.3 on 2024-03-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image4',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image5',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='image6',
            field=models.ImageField(blank=True, upload_to='service_images'),
        ),
        migrations.DeleteModel(
            name='serviceImage',
        ),
    ]
