# Generated by Django 5.0 on 2024-04-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_image1_service_image2_service_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Contact',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='Kampala', max_length=100),
        ),
    ]
