# Generated by Django 5.0 on 2024-04-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_booked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
