# Generated by Django 5.0.4 on 2024-05-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('storefront', '0033_order_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefront.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
