# Generated by Django 5.0.3 on 2024-03-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.TextField(max_length=25)),
                ('logo', models.ImageField(default='default.jpg', upload_to='business_logos')),
                ('Business_description', models.TextField(max_length=150)),
                ('location', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('Conctact', models.IntegerField()),
                ('Cartalogue', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
