# Generated by Django 5.0.3 on 2024-03-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Cartalogue',
            new_name='Catalogue',
        ),
    ]
