# Generated by Django 5.0.3 on 2024-03-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_cartalogue_business_catalogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Business_description',
            new_name='business_description',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='Conctact',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Business_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='Catalogue',
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_catalogue')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_images', to='business.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='Business name', max_length=25),
        ),
    ]
