# Generated by Django 5.0.3 on 2024-03-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_business_description_business_business_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='owner',
        ),
    ]
