# Generated by Django 5.0.3 on 2024-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.TextField(max_length=20),
        ),
    ]
