# Generated by Django 5.0.3 on 2024-03-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_business_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_catalogue_images')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogoue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='business.business')),
                ('images', models.ManyToManyField(related_name='catalogues', to='business.image')),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessImage',
        ),
    ]
