# Generated by Django 5.0.3 on 2024-03-22 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_catalogoue_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='business.business'),
        ),
        migrations.RemoveField(
            model_name='catalogue',
            name='images',
        ),
        migrations.AddField(
            model_name='catalogue',
            name='images',
            field=models.ImageField(default=None, upload_to='business_catalogue'),
        ),
    ]
