# Generated by Django 5.0.3 on 2024-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_item_remove_order_customer_remove_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('food and beverages', 'food and beverages'), ('phones', 'phones'), ('outdoor', 'outdoor'), ('indoor', 'indoor'), ('watches and jewelry', 'watches and jewelry'), ('books and stationery', 'books and stationery'), ('toys', 'toys'), ('games', 'games'), ('shoes', 'shoes'), ('bags', 'bags'), ('electronics', 'electronics'), ('health and beauty', 'health and beauty'), ('sports', 'sports'), ('furniture', 'furniture'), ('music', 'music'), ('baby', 'baby'), ('fitness and gym', 'fitness and gym'), ('kitchen and dining', 'kitchen and dining')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('t', 'tertiary')], default=None, max_length=2),
        ),
    ]
