# Generated by Django 5.0.3 on 2024-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_item_category_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
