# Generated by Django 5.0.3 on 2024-03-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('p', 'primary'), ('t', 'secondary'), ('t', 'tertiary')], default=None, max_length=1),
        ),
    ]
