# Generated by Django 5.0.3 on 2024-03-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_item_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('key_features', models.TextField(max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='storefront.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
