# Generated by Django 5.0.3 on 2024-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_alter_item_details_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary')], default=None, max_length=10),
        ),
    ]
