# Generated by Django 5.0.3 on 2024-03-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
