# Generated by Django 5.0.4 on 2024-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0012_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_details',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='description', max_length=500),
        ),
    ]
