# Generated by Django 5.0.4 on 2024-04-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0013_remove_item_details_description_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='short_description',
        ),
    ]
