# Generated by Django 5.0.4 on 2024-04-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0017_remove_order_items_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.order'),
        ),
    ]
