# Generated by Django 5.0.4 on 2024-04-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0021_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
    ]
