# Generated by Django 5.0.4 on 2024-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0024_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
    ]
