# Generated by Django 5.0.4 on 2024-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0031_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=30),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
