# Generated by Django 5.0.4 on 2024-04-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0032_order_payment_method_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
