# Generated by Django 5.0.4 on 2024-05-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0033_order_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_details',
            name='id',
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storefront.item'),
            preserve_default=False,
        ),
    ]
